Update get.yaml

diff --git a/.github/workflows/get.yaml b/.github/workflows/get.yaml
--- a/.github/workflows/get.yaml
+++ b/.github/workflows/get.yaml
@@ -11,17 +11,28 @@ jobs:
   get_name:
     runs-on: ubuntu-latest
     steps:
-    - name: set variable
-      run: |
-        exit_code=0
-        if [ $exit_code -ne 0 ]; then
-            echo "Script failed with exit code $exit_code"
-            exit $exit_code
-        fi
-    - name: run after error
-      if: always()
-      run: |
-        echo "hello"
+    - name: generate logs
+      run: echo rohit > hello.txt
+      
+    - name: Configure AWS Credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
+        
+    - name: Push Logs to S3
+      run: aws s3 cp logs.txt s3://salesforce-murli/qa/logs.txt
+    # - name: set variable
+    #   run: |
+    #     exit_code=0
+    #     if [ $exit_code -ne 0 ]; then
+    #         echo "Script failed with exit code $exit_code"
+    #         exit $exit_code
+    #     fi
+    # - name: run after error
+    #   if: always()
+    #   run: |
+    #     echo "hello"
     # - name: print name
     #   run: |
     #     echo "sdgzdsgvzsbgzgbz" >> log.txt
