Update get.yaml

diff --git a/.github/workflows/get.yaml b/.github/workflows/get.yaml
--- a/.github/workflows/get.yaml
+++ b/.github/workflows/get.yaml
@@ -13,7 +13,11 @@ jobs:
     steps:
     - name: set variable
       run: |
-        sfzszs
+        exit_code=1
+        if [ $exit_code -ne 0 ]; then
+            echo "Script failed with exit code $exit_code"
+            exit $exit_code
+        fi
     - name: run after error
       if: always()
       run: |
